### ISSUE TITLE
Fix “potential habitat” field in results table -- not sorting as anticipated.

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/FishPass#136]
Decimal issue?

**Comment by rhodges** [comment]
It sorts as a text field, since the data is textual (" mi" is appended to the numbers). If we fix the sorting, we lose the unit, and we don't have a good way of inserting the unit elsewhere. We DO NOT have a way to override the sort on that column.

Options:
* ignore this and move on
* offer a second column of just numeric values
* drop the units and hope everyone just knows it's miles
   * maybe offer additional adjacent column called "potential habitat units" that is always "mi"?
* hack the data-tables source code and hope that there's an easy method to override the sorting algorithm for a specific column only and re-write it to parse out and sort by the numeric value.

**Comment by rhodges** [comment]
look to add "(mi)" to the header.
